### ISSUE TITLE
Delete messages only on client side

### ISSUE THREAD

**Issue by karthickvkumar** [smilefam/SendBird-JavaScript#10]
Hi @sf-harry-kim, @sf-john-kim @sf-jed-kyung, In send-bird javascript sdk, can we delete messages only on the sender or receiver's side.(like in whatsApp, if i delete messages of a chat, it will delete only on my side. On the receiver the messages will still remains) In sdk i seen only [deleting a message permanently](https://docs.sendbird.com/javascript#sdk_function_common_3_7_delete_a_message). 

Thanks in Advance

**Comment by sf-harry-kim** [comment]
Hi karthickvkumar,

We don't currently fire an event for deleting message. So it doesn't synchronise on both side when deleting.

It will be deleted on receiver's side when they reload previous messages.

Regards,
Harry
