### ISSUE TITLE
many group channels lost !

### ISSUE THREAD

**Issue by MarwaAbuEssa** [smilefam/SendBird-JavaScript#13]
hi, 
i'm using the  Javscript SDK V3 and i had created a sample app includes 11 channels , i checked it using your basic-sample .
during my work in a separated app that using this sample app , suddenly the channels reduced to 1 channel !!.
i refreshed your sample app and it disappeared suddenly except this 1 channel !!.
i didn't delete any channel in my separated app .!! . this happened twice and i don't know why.

I checked sendbird dashboard and checked the channels using mesasges link and i found my 4 group channels exists !!!! so why even your basic sample app is not getting it .

any help please ??

**Comment by sf-jin-ku** [comment]
Hi MarwaAbuEssa,

3.0 had an issue generating some duplicated users that must have caused your issue. 
Could you try the latest version with new user_id?
It should fix your problem.
