### ISSUE TITLE
sendbird2.init() is not a function.

### ISSUE THREAD

**Issue by MichaelTobin18** [smilefam/SendBird-JavaScript#14]
I am following (http://blog.sendbird.com/tutorial-build-a-messaging-app-using-react-native/) for a school project and cannot get past setting up the login. I have changed all the requires to the new import syntax for react-native. The error I am getting is ... "sendbird.init is not a function" ... From what I am reading, it is a bug and I need to revert back to an older state of react-native and sendbird. 

Let me know if there is a known solution to this. Thank you.

**Comment by sf-jin-ku** [comment]
Hi Michael,

Sorry.
The guide was built on SDK v2.
Could you try v3 sample ?

Thanks.
