### ISSUE TITLE
basic sample seems to be v2 - where is v3 sample?

### ISSUE THREAD

**Issue by parijatsahai** [smilefam/SendBird-JavaScript#16]
It seems the basic-sample is still v2. Where can we download the v3 basic sample?

**Comment by rtroncoso** [comment]
Check on the `master` branch, you should be able to see this commit: https://github.com/smilefam/SendBird-JavaScript/commit/be21b65e052ab4cd2b7ec8d6f25f0dcf09ba686f, which updated basic sample to v3.0.9 of SendBird's SDK.
