### ISSUE TITLE
undefined is not a function ( evaluating 'sendbird.init' )

### ISSUE THREAD

**Issue by karthickvkumar** [smilefam/SendBird-JavaScript#2]
Hi @sf-harry-kim @sf-james-kim, Thanks for this awesome package. I tried send bird [example] (https://github.com/smilefam/SendBird-JavaScript/tree/master/tutorial-react-native-sample/SendBirdSample) in RN android, It is showing below mentioned error!

![screenshot_2016-04-26-11-21-46](https://cloud.githubusercontent.com/assets/11032434/14808264/7af3539a-0ba1-11e6-85cf-cfa6c3b43d4c.png)

It would be more helpful if you provide any solution.

Thanks in Advance

**Comment by sf-james-kim** [comment]
Sorry. 
Please download JavaScript-SDK version 2.4.8 or later.
The problem will be solved by this version.
