### ISSUE TITLE
execution failed for task ':react-native-push-notification:processReleaseResources'.

### ISSUE THREAD

**Issue by SPxiaomin** [smilefam/SendBird-JavaScript#20]
when i run the demo-SendBirdReactNativeSample  in Ubuntu, i encounter this ——

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-push-notification:processReleaseResources'.
> at index 4


```

i don't known what happen, plz help.

thx in advance.

**Comment by Alchemist85K** [comment]
@SPxiaomin 
Thank you for your interest in SendBird SDK.
So sorry the answer is late.
Do you still have the same issue?
If you still have the same problem, could you please tell me about problem more detail? (like code snippet)
