### ISSUE TITLE
I'm not getting any push notifications in React Native Android.

### ISSUE THREAD

**Issue by booboothefool** [smilefam/SendBird-JavaScript#21]
Project is set up similarly to the React Native example.

Sender ID and Server/API key is configured in dashboard. 
`registerGCMPushTokenForCurrentUser` returns success.
Client is inactive/disconnected e.g. screen is locked or exited app.

What else am I missing?

**Comment by alvelig** [comment]
Hi @booboothefool! Did you solve the problem?
