### ISSUE TITLE
FCM support for React Native

### ISSUE THREAD

**Issue by iramlg** [smilefam/SendBird-JavaScript#24]
Hello, I was trying to make my react native app use push notifications but in the JavaScript SDK there is only a registerGCMPushTokenForCurrentUser() while I am stuck on using FCM instead of GCM.

In Android you guys have support for FCM, so won't that be available for the JavaScript SDK?

**Comment by sf-jin-ku** [comment]
@iramlg 
The method should be fine for FCM as well. SendBird completely moved to FCM and we'll rename the method name momentarily.
