### ISSUE TITLE
Unable to use .sendFileMessage() after update

### ISSUE THREAD

**Issue by iramlg** [smilefam/SendBird-JavaScript#25]
Hello there, after I updated to version 3.0.22, .sendFileMessage() has broken down in react native.

I was able to get the error message using try catch:

"One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? We don't allow it, as this is an edge case that we do not support. This error is a performance optimization and not spec compliant."

Tested on 4 different devices and React Native version 0.40.0 , all had the same issue.

Here example of JSON used on image 

{
    uri: "file:/data/user/0/com.tfmessenger/cache/1487355979803.JPEG", 
    type: "image/jpeg", 
    name: "1487355979803.JPEG"
}

**Comment by iramlg** [comment]
![screenshot_20170217-173642](https://cloud.githubusercontent.com/assets/572530/23080488/0ba492a2-f538-11e6-9dda-01351c319a03.png)
![screenshot_20170217-173653](https://cloud.githubusercontent.com/assets/572530/23080487/0b9cbfc8-f538-11e6-82c8-ab7e9c3ed091.png)

I was able to get the error on dev mode!

**Comment by sf-jin-ku** [comment]
Hi 
This should be resolved in new v3.0.23 SDK and our updated sample!

Thanks!

**Comment by iramlg** [comment]
Just saved my day!

thanks
