### ISSUE TITLE
keyboard hides the textinput view in example application for react native

### ISSUE THREAD

**Issue by vidhyalakshmirbt** [smilefam/SendBird-JavaScript#26]
Hi ,
The keyboard hides the textinput field when we click on it for typing message to be sent in chat screen. 
Is there any code for handling keyboard?

**Comment by Alchemist85K** [comment]
@vidhyalakshmirbt 
Thank you for your interest in SendBird SDK.
So sorry the answer is late.
Do you still have the same issue?
There is no code for handling the keyboard.
Thank you.
