### ISSUE TITLE
text state doesn't reset

### ISSUE THREAD

**Issue by badjoras7** [smilefam/SendBird-JavaScript#27]
Hello,

When I'm running the Sendbird React Native Sample in a physical Android phone the text doesn't reset after the send button is pressed:

[https://www.youtube.com/watch?v=GWmBxukOnNQ](https://www.youtube.com/watch?v=GWmBxukOnNQ)

Can someone help?
Thanks

Regards

**Comment by bionimic** [comment]
apparently Im having the same issue. any updates?

**Comment by Alchemist85K** [comment]
@badjoras7 @bionimic 
Thank you for your interest in SendBird SDK.
So sorry the answer is late.
Do you still have the same issue?
