### ISSUE TITLE
Can't resolve 'babel-loader'

### ISSUE THREAD

**Issue by atteeela** [smilefam/SendBird-JavaScript#28]
Instructions on the README.me lead to the following error from a fresh clone

$ webpack -p
Hash: 2274d2a310759cb7fb0b
Version: webpack 2.5.0
Time: 50ms

ERROR in Entry module not found: Error: Can't resolve 'babel-loader' in '/Users/attila/git/SendBird-JavaScript/web-live-chat/src'

**Comment by Alchemist85K** [comment]
@atteeela 
Thank you for your interest in SendBird SDK.
So sorry the answer is late.
Do you still have the same issue?
Please install library with `npm install` before other command.
Thank you.
