### ISSUE TITLE
Can't find variable: XDomainRequest

### ISSUE THREAD

**Issue by designerkamal** [smilefam/SendBird-JavaScript#3]
The react-native sample fails in Android with the following error

`Can't find variable: XDomainRequest`

**Comment by sf-james-kim** [comment]
Sorry. 
Please download JavaScript-SDK version 2.4.8 or later.
The problem will be solved by this version.
https://github.com/smilefam/SendBird-SDK-JavaScript

**Comment by nlively** [comment]
I upgraded to 2.4.8.  This did not fix the issue.  I am using iOS

I expanded the minified SendBird.min.js file and discovered that the XDomainRequest line is still invoked because the condition wrapping it evaluates to "true".

Consider adding "&& navigator.product != 'ReactNative'" to the condition

**Comment by designerkamal** [comment]
@sf-james-kim, like @nlively mentioned , 2.4.8 did not solve the react-native issue.

Currently using the following line of code in my test project to step around this issue ;)
window.navigator.userAgent = "react-native msie 11";

**Comment by nlively** [comment]
@designerkamal, I get errors when I try to reference window.navigator.
Using iOS. 

Thoughts?

**Comment by designerkamal** [comment]
@nlively the above code worked for me in iOS simulator with react-native 0.24.1.

**Comment by sf-james-kim** [comment]
@nlively @designerkamal 
 
Sorry. 
2.4.8 version has bug about check to IE.
Please download JavaScript-SDK version 2.4.9 or later.

https://github.com/smilefam/SendBird-SDK-JavaScript
