### ISSUE TITLE
Cannot read property 'stop' of null

### ISSUE THREAD

**Issue by panhna** [smilefam/SendBird-JavaScript#30]

**Comment by panhna** [comment]
![screen shot 2017-05-21 at 10 56 53 pm](https://cloud.githubusercontent.com/assets/5246440/26285386/e2448536-3e78-11e7-9d3c-440f839b29b6.png)

**Comment by sf-jin-ku** [comment]
@panhna which sdk version are you using? have you tried the latest version, 3.0.29?

**Comment by panhna** [comment]
👍  my version is 3.0.25.
@sf-jin-ku ok let me try the last one. thx
