### ISSUE TITLE
Help me, when i try run project (react native), error No resource found that matches the given name ...

### ISSUE THREAD

**Issue by Dung1128** [smilefam/SendBird-JavaScript#32]
E:\AgileProject\sendbird\SendBird-JavaScript\react-native-sample\SendBirdReactNativeSample\node_modules\react-native-fs\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\drawable\abc_item_background_holo_dark.xml:20:118-164 : No resource found that matches the given name (at 'drawable' with value '@drawable/abc_list_selector_disabled_holo_dark').
E:\AgileProject\sendbird\SendBird-JavaScript\react-native-sample\SendBirdReactNativeSample\node_modules\react-native-fs\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\drawable\abc_item_background_holo_dark.xml:21:118-164 : No resource found that matches the given name (at 'drawable' with value '@drawable/abc_list_selector_disabled_holo_dark').
E:\AgileProject\sendbird\SendBird-JavaScript\react-native-sample\SendBirdReactNativeSample\node_modules\react-native-fs\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\drawable\abc_item_background_holo_light.xml:20:118-165 : No resource found that matches the given name (at 'drawable' with value '@drawable/abc_list_selector_disabled_holo_light').
E:\AgileProject\sendbird\SendBird-JavaScript\react-native-sample\SendBirdReactNativeSample\node_modules\react-native-fs\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\drawable\abc_item_background_holo_light.xml:21:118-165 : No resource found that matches the given name (at 'drawable' with value '@drawable/abc_list_selector_disabled_holo_light').
E:\AgileProject\sendbird\SendBird-JavaScript\react-native-sample\SendBirdReactNativeSample\node_modules\react-native-fs\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\drawable\abc_list_selector_holo_dark.xml:22:118-164 : No resource found that matches the given name (at 'drawable' with value '@drawable/abc_list_selector_disabled_holo_dark').
E:\AgileProject\sendbird\SendBird-JavaScript\react-native-sample\SendBirdReactNativeSample\node_modules\react-native-fs\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\drawable\abc_list_selector_holo_dark.xml:23:118-164 : No resource found that matches the given name (at 'drawable' with value '@drawable/abc_list_selector_disabled_holo_dark').
E:\AgileProject\sendbird\SendBird-JavaScript\react-native-sample\SendBirdReactNativeSample\node_modules\react-native-fs\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\drawable\abc_list_selector_holo_light.xml:22:118-165 : No resource found that matches the given name (at 'drawable' with value '@drawable/abc_list_selector_disabled_holo_light').
E:\AgileProject\sendbird\SendBird-JavaScript\react-native-sample\SendBirdReactNativeSample\node_modules\react-native-fs\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\drawable\abc_list_selector_holo_light.xml:23:118-165 : No resource found that matches the given name (at 'drawable' with value '@drawable/abc_list_selector_disabled_holo_light').
E:\AgileProject\sendbird\SendBird-JavaScript\react-native-sample\SendBirdReactNativeSample\node_modules\react-native-fs\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\drawable\abc_textfield_search_material.xml:18:87-138 : No resource found that matches the given name (at 'drawable' with value '@drawable/abc_textfield_search_activated_mtrl_alpha').
E:\AgileProject\sendbird\SendBird-JavaScript\react-native-sample\SendBirdReactNativeSample\node_modules\react-native-fs\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\drawable\abc_textfield_search_material.xml:19:89-140 : No resource found that matches the given name (at 'drawable' with value '@drawable/abc_textfield_search_activated_mtrl_alpha').
E:\AgileProject\sendbird\SendBird-JavaScript\react-native-sample\SendBirdReactNativeSample\node_modules\react-native-fs\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\drawable\abc_textfield_search_material.xml:20:58-107 : No resource found that matches the given name (at 'drawable' with value '@drawable/abc_textfield_search_default_mtrl_alpha').
E:\AgileProject\sendbird\SendBird-JavaScript\react-native-sample\SendBirdReactNativeSample\node_modules\react-native-fs\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\drawable\abc_textfield_search_material.xml:21:29-78 : No resource found that matches the given name (at 'drawable' with value '@drawable/abc_textfield_search_default_mtrl_alpha').

**Comment by Alchemist85K** [comment]
@Dung1128 
Thank you for your interest in SendBird SDK.
So sorry the answer is late.
Do you still have the same issue?
If you still have the same problem, could you please tell me about problem more detail?
Thank you.
