### ISSUE TITLE
gl-react-native module is not avaiable

### ISSUE THREAD

**Issue by mrkentlng** [smilefam/SendBird-JavaScript#33]
i try to run react-native sendbird demo but got this issue like picture below here:
[
<img width="387" alt="screen shot 2017-07-31 at 4 12 51 pm" src="https://user-images.githubusercontent.com/12961488/28770974-4a4e1c0e-760b-11e7-9741-87df3827c3bf.png">
](url)
Please help me

**Comment by Alchemist85K** [comment]
@mrkentlng 
Thank you for your interest in SendBird SDK.
So sorry the answer is late.
Do you still have the same issue?
If you still have the same problem, could you please tell me about problem more detail?
Thank you.
