### ISSUE TITLE
sb = SendBird.getInstance(); return null

### ISSUE THREAD

**Issue by ravirupareliya** [smilefam/SendBird-JavaScript#38]
As per this sample i have try to implement it in my project 

    import SendBird from 'sendbird'
    var sb = null;
    sb = SendBird.getInstance();

But it is showing `sb` as null

![sendbird](https://user-images.githubusercontent.com/17959204/32644289-9b340f0c-c606-11e7-9ea1-509fb9ffe6a8.png)

**Comment by Alchemist85K** [comment]
@ravirupareliya 
Thank you for your interest in SendBird SDK.
So sorry the answer is late.
`getInstance()` is a function to get a SendBird instance that has already been created by new.
