### ISSUE TITLE
undefined is not an object (evaluating 'this._component.getScrollableNode')

### ISSUE THREAD

**Issue by vladimir830** [smilefam/SendBird-JavaScript#39]
I am getting this error when I am trying to fetch my group channel list.
![simulator screen shot - iphone 7 - 2017-12-12 at 11 14 47](https://user-images.githubusercontent.com/31650214/33862288-acf0f710-df2d-11e7-93fe-6cf02ed27009.png)

  componentDidMount() {

    sb = SendBird.getInstance();
    var listQuery = sb.GroupChannel.createMyGroupChannelListQuery();

    if (listQuery.hasNext) {
      listQuery.next(function(channelList, error){
        if (error) {
          console.error(error);
          return;
        }

        alert(JSON.stringify(channelList))
        console.log(channelList);
      });
    }
  }

How can I fix this?

**Comment by Alchemist85K** [comment]
@vladimir830 
Thank you for your interest in SendBird SDK.
So sorry the answer is late.
Do you still have the same issue?
If you still have the same problem, could you please tell me about problem more detail? (like code snippet)
