### ISSUE TITLE
Problems in React Native

### ISSUE THREAD

**Issue by nlively** [smilefam/SendBird-JavaScript#4]
It seems that #3 is still not resolved in version 2.4.8.

I still get the "XDomainRequest is not defined" error when using the library on iOS.

**Comment by nlively** [comment]
If anyone has a workaround to this, please paste a full code snippet.  Someone referenced a "window.navigator.userAgent" hack, but (at least in the iOS simulator), window.navigator is not recognized.

**Comment by karthickvkumar** [comment]
+1

**Comment by sf-james-kim** [comment]
@karthickvkumar @nlively 

Sorry. 
2.4.8 version has bug about check to IE.
Please download JavaScript-SDK version 2.4.9 or later.

https://github.com/smilefam/SendBird-SDK-JavaScript

**Comment by sf-james-kim** [comment]
@karthickvkumar @nlively

Sorry again.
Please download JavaScript-SDK version 2.4.10 or later.
