### ISSUE TITLE
Does sendBird SDK works well with create-react-native-app ?

### ISSUE THREAD

**Issue by kevinleeTCA** [smilefam/SendBird-JavaScript#42]
I got a project setting up using [create-react-native-app](https://facebook.github.io/react-native/docs/getting-started.html).

It got [`Expo`](https://docs.expo.io/versions/latest/index.html) build in, which is used to build and deploy mobile binaries. 

I try to hook up `SendBird` with the project.
`yarn add sendbird`
but it is always null when I trying to get the instance.
`sb = SendBird.getInstance();`
`sb` is always null. Am I missing something here ?

I tried the [demo program](https://github.com/smilefam/SendBird-JavaScript), it works all fine. 

Just wondering if we have to [eject from expo](https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md) in order to make sendbird SDK work? thanks.

Does `SendBird` user `react-native link` to link the project ?

**Comment by gianpaj** [comment]
First, you need to initialize the `SendBird` instance:
https://docs.sendbird.com/javascript#authentication_3_initializing_with_app_id

then you can get the Instance in other components from a global variable. At least that's the theory I'm also trying to integrate with SendBird :)

**Comment by kevinleeTCA** [comment]
@gianpaj you are right, I need to provide an API key to create an instance of the application. Generally, does anyone hooked up the SDKs based on create-react-native-app?

**Comment by gianpaj** [comment]
I found these Github repos:
- https://github.com/saitoxu/SendBirdSample
- https://github.com/cloudprogrammer/NativeBird
- https://github.com/nsuarezcanton/redux-sendbird-example

If I can make a 1-on-1 chat work, I'll post an example here.
It's more difficult than what I thought. 😕

**Comment by Alchemist85K** [comment]
@kevinleeTCA 
Thank you for your interest in SendBird SDK.
So sorry the answer is late.
Do you have other issue?
If you have problem, please send e-mail at support@sendbird.com.

**Comment by lionhive** [comment]
SendBird starts at $599/mo for cheapest package, pretty expensive compared to competitive products.

**Comment by Alchemist85K** [comment]
@lionhive 
Thank you for your interest in SendBird.
If you talk to our sale team, you'll can find various pricing policies.
Please contact sale@sendbird.com . Thank you.
