### ISSUE TITLE
[Request] Online working demo

### ISSUE THREAD

**Issue by cosecantt** [smilefam/SendBird-JavaScript#45]
We would like to see online web demo before integrate it.
Thanks.

**Comment by Alchemist85K** [comment]
@cosecantt 
Thank you for your interest in SendBird SDK.

We have 2 online sample.
widget sample: https://sample.sendbird.com/widget/
live chat sample : https://sample.sendbird.com/livechat/

For more information, please contact sales@sendbird.com.
Thank you.
