### ISSUE TITLE
cannot implement sample widget in my reactjs dashboard

### ISSUE THREAD

**Issue by jadelmir** [smilefam/SendBird-JavaScript#48]
I cloned the repository took web-widget , and added to my src folder 
then I imported as prescibed 
import '../../web-widget/SendBird.min';
import '../../web-widget/build/widget.SendBird';

I added a div in my react component 	<div id="sb_widget" />

an error occurred

 ./src/web-widget/SendBird.min.js
  Line 5:  'define' is not defined  no-undef
  Line 5:  'define' is not defined  no-undef
  Line 6:  'e' is not defined       no-undef

Search for the keywords to learn more about each error.

please can someone help me to implement the widget in my app

**Comment by rubelux** [comment]
@jadelmir I am having the same problem, can you help?

Thanks
