### ISSUE TITLE
undefined is not a object(evaluating 'navigator.userAgent.toLowerCase' ) 

### ISSUE THREAD

**Issue by karthickvkumar** [smilefam/SendBird-JavaScript#5]
Hi @sf-harry-kim @sf-james-kim, I tried send bird [example](https://github.com/smilefam/SendBird-JavaScript/tree/master/tutorial-react-native-sample/SendBirdSample) in RN android, It is showing below mentioned error.

Screenshot of the errror message
![screenshot_2016-05-10-10-51-00](https://cloud.githubusercontent.com/assets/11032434/15136471/7be9de46-169f-11e6-8b33-d40d6d3f216e.png)

Its showing the above mentioned error for this package
![selection_012](https://cloud.githubusercontent.com/assets/11032434/15136483/9dff513c-169f-11e6-8934-5a001c094f0e.png)

**Comment by sf-james-kim** [comment]
@karthickvkumar 

Sorry.
Please download SendBird-SDK version 2.4.10 or later.

https://github.com/smilefam/SendBird-SDK-JavaScript

**Comment by karthickvkumar** [comment]
Thanks @sf-james-kim  its working fine in 2.4.10

**Comment by Kavita0357** [comment]
have an error of undefined is not an object window.navigator.useragent.tolowercase
in react-native in react-vr-player
I'm not using sendbird
