### ISSUE TITLE
how to implement the widget in reactjs app 

### ISSUE THREAD

**Issue by jadelmir** [smilefam/SendBird-JavaScript#51]
in the index.html I added the 

	<div id="sb_widget"></div>
and  
   <script src="web-widget/SendBird.min.js"></script>
    <script src="web-widget/build/widget.SendBird.js"></script>
    <script>
      sbWidget.start(Appid);
    </script>

it works fine but I need to implement it in my react app 
my scripts  still in index.html but I put the div 	(<div id="sb_widget"></div>) in my app.js
but nothing happened is isn't working anymore 

so how could I implement it in a reactjs app ??

**Comment by Alchemist85K** [comment]
Hi @jadelmir .
We added a guide document to combine to ReactJS.
Please, check the link below.
https://github.com/smilefam/SendBird-JavaScript/blob/master/web-widget/CUSTOMIZE.md

Thank you for your interest in SendBird SDK.

**Comment by jadelmir** [comment]
thank you @Alchemist85K  I Glad to hear from  

I followed the intructions,sadly I am new with webpack  but when I am rebuilding using webpack -p
results the following error 

Hash: 18138ec5a7d4b25b1579
Version: webpack 4.12.0
Time: 1766ms
Built at: 2018-06-25 10:54:23
 1 asset
[124] (webpack)/buildin/global.js 489 bytes {0} [built]
[125] ./js/widget.js 273 bytes {0} [built] [failed] [1 error]
[328] multi babel-polyfill ./js/widget.js 40 bytes {0} [built]
    + 326 hidden modules

ERROR in ./js/widget.js
Module build failed (from ../node_modules/eslint-loader/index.js):
TypeError: Cannot read property 'eslint' of undefined
    at Object.module.exports (/Users/developer1/Desktop/SendBird-JavaScript/web-widget/node_modules/eslint-loader/index.js:148:18)
 @ multi babel-polyfill ./js/widget.js

**Comment by Alchemist85K** [comment]
@jadelmir 
The widget sample used `webpack version 2`.
Please check again with webpack version 2.
Thanks.

**Comment by rubelux** [comment]
Hi, I have been trying to get this work in Reactjs for a while now with no luck.

I followed the guide but the compiled ```widget.SendBird.js``` is exported with AMD modules support via the ```libraryTarget: 'umd'``` command in Webpack. I do not know why but React gives an error saying that define is undefined.

Thanks

**Comment by ViniciusGularte** [comment]
@rubelux  same problem here, you managed to find a Solution ? sorry for resurrecting the issue

**Comment by janna-sendbird** [comment]
Hi @ViniciusGularte are you using the latest version of the SendBird sample app web-widget and working with the guide here? There should be an .eslintrc.js file in your app directory that has the rule "no-undef":"warn" as mentioned here: https://github.com/sendbird/SendBird-JavaScript/blob/master/web-widget/CUSTOMIZE.md#customizing-eslint

**Comment by mfebrianto** [comment]
Hi I have another issue implementing the widget on my reactjs application. After I built it and copy the widget.SendBird.js it is shown error ```Line 1:  Expected an assignment or function call and instead saw an expression  no-unused-expressions```. Can anyone please help ? Thank you

**Comment by janna-sendbird** [comment]
@mfebrianto It looks like you may be missing the `.eslintrc.js` file from this step
https://github.com/sendbird/SendBird-JavaScript/blob/master/web-widget/CUSTOMIZE.md#customizing-eslint

Please note that this should be under the `/my-app` folder and should end in **.js** or it will not be recognized (I encountered the no-unused-expression issue when it was not saved as `.eslintrc.js`).
