### ISSUE TITLE
[sample widget] Duplication of users list in New Chat window

### ISSUE THREAD

**Issue by FlorianNextdoor** [smilefam/SendBird-JavaScript#52]
Hello, I observ a small issue with the sample widget:

When you want to start a new chat, the list of users that appears in the "new chat" window duplicates itself endlessly as you scroll.
Do you think I can fix this little problem easily in src javascript?
![sendbirdissue1](https://user-images.githubusercontent.com/32170736/42772505-f1f8cfd4-892a-11e8-9ce6-d001f28b0db5.JPG)
![sendbirdissue2](https://user-images.githubusercontent.com/32170736/42772524-01e07168-892b-11e8-865e-972a41d584f3.JPG)
![sendbirdissue3](https://user-images.githubusercontent.com/32170736/42772527-0409f3ec-892b-11e8-8aa9-f2235df6d90e.JPG)

Thank you so much! 

My user list in my dashboard is clean : no double

**Comment by chrisallo** [comment]
We just fixed the issue and applied to the sample.
Really appreciate to your report.

**Comment by FlorianNextdoor** [comment]
Great, it works.
Thank you very much for your efficiency

**Comment by Alchemist85K** [comment]
Hi @FlorianNextdoor .
We fixed the issue and deployed.
Thank you for your interest in SendBird.

**Comment by FlorianNextdoor** [comment]
Thank you again  for your efficiency !
