### ISSUE TITLE
[sample widget] Search User with nickname

### ISSUE THREAD

**Issue by FlorianNextdoor** [smilefam/SendBird-JavaScript#53]
Hello, 
 
Is there any way to search an user with nickname directly from the view?
 
I explain myself, when you want to create a message, you select the user (or users) to send the message to, but the only way to find a specific user is to scroll. So I would like to integrate a search input directly from the new message window (as on the picture).
 
I saw that the `this.sb.createUserListQuery()` (in sendbird.js) method makes a query and loads users **20 by 20**, and in the chat-section.js the `addUserListScrollEvent()` method loads the next 20 by scrolling. 
 
So what I'm doing right now: I automatically load 20 by 20 users (without scroll), so I can search for a user via my input. But it's not clean and it takes time. 
Moreover, I would have more than 5000 users, it will take more than 10 minutes to load, I can not leave on this solution.
 
So my question: is it possible to make a nickname query? So that a user can easily find his correspondent?

![sendbirdissue4](https://user-images.githubusercontent.com/32170736/43068814-c335c7d8-8e6b-11e8-9e98-0d9e1c42692f.JPG)

**Comment by Alchemist85K** [comment]
Hi @FlorianNextdoor .
We don't provide the method to find users using nicknames.
For more information, please send an email support@sendbird.com .
Thank you.
