### ISSUE TITLE
Chat widget not working in Microsoft Edge browser

### ISSUE THREAD

**Issue by Boomcollective** [smilefam/SendBird-JavaScript#54]
We have integrated java script SDK in our website. We are not able to send message or close the chat window in Microsoft Edge browser. Infact, most of the features in not supported in Edge browser. Even the latest demo is not working in Edge browser.

https://sample.sendbird.com/widget/

Can you look into this and update us.

**Comment by shaileshe2logy** [comment]
We are also getting same issue. Is there any solution available from SendBird?

**Comment by Alchemist85K** [comment]
Hi @Boomcollective @shaileshe2logy .
we'll check and let you know.
Thank you for your interest in SendBird SDK.

**Comment by Alchemist85K** [comment]
@Boomcollective @shaileshe2logy 
There is an issue in the part on editing css in js with Edge browser.
We'll resolve this issue and deploy it.

HTMLElement Style: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style

**Comment by Alchemist85K** [comment]
Now Widget-Sample works fine in the Edge browser.
Thank you for your interest in SendBird SDK.
