### ISSUE TITLE
Is push notification enabled?

### ISSUE THREAD

**Issue by KPkun** [smilefam/SendBird-JavaScript#55]
Can anyone confirm is push notification feature is enabled for the react-native and redux implementation of this project?

**Comment by Alchemist85K** [comment]
Hi @KPkun  ~.
Thank you for your interest in SendBird SDK. :)
We provide sample about how to use push notification in react-native-redux-sample and provide guide in official documentation.

* react-native-redux-sample
https://github.com/smilefam/SendBird-JavaScript/tree/master/react-native-redux-sample
* push notification documentation
https://docs.sendbird.com/javascript/push_notifications

**Comment by KPkun** [comment]
Thanks, @Alchemist85K 

Will look into the project and try building one.
Also, something's bothering me for a while now, because we use FCM for enabling Push Notifications for Android, does it work in mainland China?  FCM being firebase being Google?

**Comment by Alchemist85K** [comment]
FCM works in China.
If it does not work, you'll need to use something else such as Baidu push.
Baidu push support is on our road-map, but the exact date has not been set yet.
Thank you.

* FCM: https://firebase.google.com/docs/cloud-messaging/
