### ISSUE TITLE
Integrate Web widget with Reactjs

### ISSUE THREAD

**Issue by pedrobeiraof** [smilefam/SendBird-JavaScript#56]
When I try to follow CUSTOMIZE.me steps I end up with an error while importing 'widget.SendBird.js' file.

this is the error:
`TypeError: __WEBPACK_IMPORTED_MODULE_4__widget_SendBird___default.a.start is not a function`

**Comment by Alchemist85K** [comment]
@pedrobeiraof 
Thank you for your interest in SendBird SDK. :)
Is that an error that appears when you run "webpack -p" command to create a "widget.SendBird.js" file? Or did you have a problem on calling "SendBirdWidget.start()" in your React project?
Could you give us more information about your environment, such as your node version, npm version, webpack version and so on.
Widget Sample is using webpack 2. Thank you for checking the webpack version.

**Comment by Alchemist85K** [comment]
@pedrobeiraof 
It is recommended that you create files through the "webpack -p" command rather than using the sample file provided.

Please, follow below.
1. Download sample projects
2. Install packages
```
cd web-widget
npm install 
```
3. Modify Files(https://github.com/smilefam/SendBird-JavaScript/blob/master/web-widget/CUSTOMIZE.md#modify-widget-sample)
4.Build(https://github.com/smilefam/SendBird-JavaScript/blob/master/web-widget/CUSTOMIZE.md#rebuild-widget-sample)

**Comment by pedrobeiraof** [comment]
it worked! thanks for the quick answer and for the great project :)

**Comment by tiagobsbraga** [comment]
What I'm doing wrong?

`ERROR in ./node_modules/sendbird/SendBird.min.js
Module not found: Error: Can't resolve 'child_process' in '/Users/tiagobraga/Documents/work/web/learning/sendbird/SendBird-JavaScript/web-widget/node_modules/sendbird'
 @ ./node_modules/sendbird/SendBird.min.js 6:5613-5637
 @ ./src/js/adapter.js
 @ ./src/js/widget.js
 @ multi babel-polyfill ./src/js/widget.js

ERROR in ./node_modules/sendbird/SendBird.min.js
Module not found: Error: Can't resolve 'fs' in '/Users/tiagobraga/Documents/work/web/learning/sendbird/SendBird-JavaScript/web-widget/node_modules/sendbird'
 @ ./node_modules/sendbird/SendBird.min.js 6:5580-5593
 @ ./src/js/adapter.js
 @ ./src/js/widget.js
 @ multi babel-polyfill ./src/js/widget.js`

**Comment by gururajphadnis** [comment]
> What I'm doing wrong?
> 
> `ERROR in ./node_modules/sendbird/SendBird.min.js
> Module not found: Error: Can't resolve 'child_process' in '/Users/tiagobraga/Documents/work/web/learning/sendbird/SendBird-JavaScript/web-widget/node_modules/sendbird'
> @ ./node_modules/sendbird/SendBird.min.js 6:5613-5637
> @ ./src/js/adapter.js
> @ ./src/js/widget.js
> @ multi babel-polyfill ./src/js/widget.js
> 
> ERROR in ./node_modules/sendbird/SendBird.min.js
> Module not found: Error: Can't resolve 'fs' in '/Users/tiagobraga/Documents/work/web/learning/sendbird/SendBird-JavaScript/web-widget/node_modules/sendbird'
> @ ./node_modules/sendbird/SendBird.min.js 6:5580-5593
> @ ./src/js/adapter.js
> @ ./src/js/widget.js
> @ multi babel-polyfill ./src/js/widget.js`

facing same issue

**Comment by tiagobsbraga** [comment]
@pedrobeiraof can you help us?

**Comment by janna-sendbird** [comment]
Hi everyone, Janna here from SendBird! There is currently an issue building this sample with JavaScript SDK version 3.0.119. The team is hard at work on a fix for the next version. In the meantime, please build with JS SDK v3.0.118.

**Comment by tiagobsbraga** [comment]
Thank you @janna-sendbird! 

But I still can't run the project. 

**Output error**
Failed to compile.

./src/widget.SendBird.js
  Line 1:1:       Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:112:     'define' is not defined                                                no-undef
  Line 1:123:     'define' is not defined                                                no-undef
  Line 1:506:     Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:967219:  Expected an assignment or function call and instead saw an expression  no-unused-expressions

Search for the keywords to learn more about each error.

---

My package.json in my project example
`{
  "name": "example",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1",
    "sendbird": "3.0.118"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
`

**Comment by janna-sendbird** [comment]
Hi @tiagobsbraga did you run **npm run eject** under your example folder (it's the my-app folder mentioned in the CUSTOMIZE.md file)? When I ran that, this added additional dependencies

**Comment by tiagobsbraga** [comment]
Untracked files... Sorry!
Works now.

**Comment by gaweki** [comment]
how to run watch as setting in CUSTOMIZE.md?

**Comment by gaweki** [comment]
try in new cra , still give me this error (without 'define 'is not defined)
![Screen Shot 2020-04-07 at 20 23 59](https://user-images.githubusercontent.com/24468078/78675318-16ab0b00-790f-11ea-9c0d-236e614712d3.png)
