### ISSUE TITLE
[sample widget] how to hide logout?

### ISSUE THREAD

**Issue by dkrishnaprasad** [smilefam/SendBird-JavaScript#58]
we are using sample: https://sample.sendbird.com/widget/

it initially shows login with userid & nickname and start chat. once we start chat, on the top it shows 'logout' (when click on settings icon).

However, we are directly showing channel (instead of asking userid and nickname) after user login in our application and we have our own logout functionality and we don't want to show the logout icon in the widget. Is there any API call to hide logout url?

I am showing widget using below call:
sbWidget.startWithConnect(appId, userId, nickname, function() {}); 
and want to **hide logout** in the widget. pls help.

**Comment by chrisallo** [comment]
I couldn't follow the context. Would you let me know what it means by hide logout?

**Comment by dkrishnaprasad** [comment]
I have changed the code in  SendBird-JavaScript\web-widget\src\js\elements\list-board.js and it is working .thanks. closing the issue
