### ISSUE TITLE
There is some way to filter users one each other?

### ISSUE THREAD

**Issue by wenderjean** [smilefam/SendBird-JavaScript#60]
Hey,

We are implementing `sendbird + widget` in our platform but we have a particular case where clients can only see support users on chat users list, they cannot see another clients, for example.

We can manage widget's online users list to filter what kind of users a specific user can see?
Also, we can disable logout button on `widget`?

Thanks

**Comment by Alchemist85K** [comment]
Hi @wenderjean 

We provide some filter as userIds, metaDataKey, and metaDataValue in `UserListQuery`.
Please, follow below.
```
const sb = new SendBird({ appId: 'YOUR_APP_ID' });
let query = sb.createUserListQuery();
// let query = sb.createUserListQuery(['user_id_1', 'user_id_2']);
query.metaDataKey = 'key';
query.metaDataValue = 'value';
query.next(function(res, err) {
    console.log(res, err);
});
```
If you want to disable logout button, you can modify the code as the conditions you want.
Thank you for your interest in SendBird SDK. :)

**Comment by wenderjean** [comment]
Hey @Alchemist85K , but is possible to tell `widget` to follow my query when rendering the list of users to start a chat?

**Comment by Alchemist85K** [comment]
@wenderjean .
The sample is initializing the `userListQuery` variable when starting a new chat.
Please modify the sample you download, if you don't want to it.
Thanks.
