### ISSUE TITLE
Cannot get group list using  sendbird's javascript sdk

### ISSUE THREAD

**Issue by arausly** [smilefam/SendBird-JavaScript#62]
I followed the api spec for getting the group list , but still get an **empty array**, when there are existing groups.
I have already connected to my sendbird's instance with the required APP_ID and in the function below I pass the sendbird instance as a parameter, then make a call to get group list. 

![send_birdissue](https://user-images.githubusercontent.com/23234383/46385056-c87dd180-c6b1-11e8-9594-334d9a181676.PNG)

**Comment by chrisallo** [comment]
Sounds weird. This query should return the list of channels that you joined. If you don't mind, please check that the user is in joined state for the channels? Or hand me the app ID so that we could check that out. Thanks.

**Comment by arausly** [comment]
oh I neglected that fact out but thanks any way. I intend to get a list of all group channels within the app. I can't see any spec around that in the doc for javascript sdk. would like help in this. Thanks

**Comment by arausly** [comment]
I later found how to achieve this by following the platform api's spec [https://docs.sendbird.com/platform/group_channel#3_list_channels](url) to get all groups
