### ISSUE TITLE
Is redux really necessary?

### ISSUE THREAD

**Issue by Jacky9425** [smilefam/SendBird-JavaScript#64]
Hi, is it possible not to implement redux in the chat project because i am very new to react native, and its quite difficult to understand redux in a short period of time.

**Comment by Alchemist85K** [comment]
@Jacky9425 
We have a React-Native sample that doesn't use Redux. See the link below.

https://github.com/smilefam/SendBird-JavaScript/tree/master/react-native-sample/SendBirdReactNativeSample

Unfortunately, the sample was deprecated. So we have no plan to update in the future. 
But I think it'll help you do what you're trying to do.

Thank you for your interest in SendBird SDK. :)

**Comment by Jacky9425** [comment]
@Alchemist85K So even it is deprecated, the code still can be reuse?

**Comment by chrisallo** [comment]
@Jacky9425 Redux is just a kind of design principle that modulizes each operation flow in order to reduce code complexity and prevent possible error. It's not must-have, though, Redux is popular for its practical advantage especially when working as a team.
