### ISSUE TITLE
How to configure the app to able to push notifications?

### ISSUE THREAD

**Issue by Jacky9425** [smilefam/SendBird-JavaScript#66]
Hi, i have looked through the source code for React-native-redux-sample for SendBird-JavaScript, and I had done installing all the needed packages. However i still not able to send or receive any notification when i sent messages to group channels.

May i know any steps i had missed to implement the notification feature?
Steps i've done:
1. install react-native-fcm and follows the given instructions to configure.
2. enable push notification on SendBird DashBoard.
3. paste the server ID and sender ID from firebase cloud messaging (extra, not mentioned in the guide)

Thank you

**Comment by chrisallo** [comment]
If you're running your own Firebase app, you'd better switch Firebase configuration files: google-services.json for Android and GoogleServices-Info.plist for iOS. Plus, open iOS app in XCode and go to Project Settings > Capatilities, then enable push notifications and background service - make sure that you have no error in push notifications authorization part.

We recommend to use `react-native-firebase` instead because `react-native-fcm` is deprecated and outdated. We're prepping for the documentation to setup push notification with `react-native-firebase` and update the sample to use it soon.

**Comment by Jacky9425** [comment]
Is the deprecated `react-native-fcm` not working at all? Cause i tried the deprecated react-native only sample and its still working (notification not working as well due to GCM).

**Comment by chrisallo** [comment]
It DOES work for now, at least. The term `deprecated` usually means that it would be updated no longer and not guarantee to work well later (or could be removed someday). It's up to you to commit to `react-native-fcm` or switch to `react-native-firebase` because it actually works just fine :)

**Comment by Jacky9425** [comment]
Then i really need some help with the notification setup as i had followed all the steps on `react-native-fcm` and also in SendBird. I am testing the react-native-redux-sample on my device and emulator, and the notification is not working. 

Do I need to initialize the firebase API /server key in the source code or just follow the setup in the docs provided (As far as i tried, no notification appear on my phone or emulator)?

**Comment by chrisallo** [comment]
I am not sure which point is in trouble. For better understanding of the problem, you'd better share all your steps you tried with settings. It's complicated for me to know how to handle it so far.

**Comment by diljithvandanam** [comment]
Hi,
i am also facing the same issue, for me i had used react-native-firebase and i am getting all other push notifications except sendbird chat notification
things i am facing:-
- able to send sample notification from firebase console
- i had added API key but the interface not allowing me to add sender id
- able to send and receive messages in sendbird, but not getting push notifications
