### ISSUE TITLE
Upload image as group channel coverUrl

### ISSUE THREAD

**Issue by Jacky9425** [smilefam/SendBird-JavaScript#67]
i have managed to change the cover image of particular group channel/group chat. However it is only a local storage (meaning even the group image updated, it only can be viewed on the device containing the image url). How do i upload it into sendbird server so that the image sync across users' devices?

**Comment by chrisallo** [comment]
Use `channel.updateChannel()` to upload cover image. There's `channelCover` property in `GroupChannelParams` so that you could upload your image as cover.

**Comment by chrisallo** [comment]
Image sync problem is usually because of cached image. You can refresh your profile image everytime by appending ?ts=[timestamp] to its URL. For example in JavaScript,
```js
const profileUrl = member.profileUrl + '?ts=' + new Date().getTime()
```

**Comment by Jacky9425** [comment]
i tried to log the url of the uploaded image and this is what i get

''content://com.newsb.provider/app_images/Pictures/images/[image].jpg''

**Comment by chrisallo** [comment]
You did it with React Native? The protocol looks like a content provider in Android. For React Native, you’d better use `Blob` to upload image. If you put the local URL as profileUrl, then it just sets it as-is.

**Comment by Jacky9425** [comment]
yes i am using React Native. Here is my code, can you explain further the `Blob` you mentioned with it?

`var _Self = this;
        // var source = [];

        ImagePicker.showImagePicker(options, (response) => {
            if (response.didCancel){
                console.log('user canceled image picker');
            }
            else if (response.error){
                console.log('imagePicker error', response.error);
            }
            else if (response.customButton){
                console.log('customised clicked', response.customButton);
            }
            else{
                source = {uri:response.uri};
                console.log(source);
                // const source = { uri: 'data:image/jpeg;base64,' + response.data };
                
                if(response.name){
                    source['name'] = response.fileName
                } else {
                    paths = response.uri.split("/")
                    source['name'] = paths [paths.length-1];
                }

                if(response.type){
                    source['type'] = response.type;
                }
                
                this.setState({
                    profileUrl: response.uri,
                });
               `

**Comment by chrisallo** [comment]
I got this. You can upload profile image by passing `source` to `sb.updateCurrentUserInfoWithProfileImage()`.

**Comment by Jacky9425** [comment]
Hi, i tried with the `sb.updateCurrentUserInfoWithProfileImage()` and nothing happens. And i cannot set the state of `profileUrl` to `source`, it will return error. The following code is the update user info function when button pressed.

`_onUpdateProfile() {
        var sb = SendBird.getInstance();
        var _Self = this;
        
        sb.updateCurrentUserInfo(_Self.state.nickname, _Self.state.profileUrl, (user, error) => {
            if(error){
                console.log(error);
                return;
            }
            ToastAndroid.show('Profile Updated!', ToastAndroid.LONG);
            this.props.navigator.replace({name:'groupChannel', refresh: _Self.props.route.refresh});
        });
    }`

**Comment by Jacky9425** [comment]
Hi, i have a new issue where when upload an image picked from gallery, the app returns error log showing `{name: "SendBirdException", code: 800220, message: "Request failed."}`. However, if upload an image taken from camera directly, the profile image is still able to upload and update successfully.

May i know what is the issue here?

Function to display picked image from gallery/camera
`_changeProfileImg(){
        var _Self = this;
        // var source = [];

        ImagePicker.showImagePicker(options, (response) => {
            if (response.didCancel){
                console.log('user canceled image picker');
            }
            else if (response.error){
                console.log('imagePicker error', response.error);
            }
            else if (response.customButton){
                console.log('customised clicked', response.customButton);
            }
            else{
                source = {uri:response.uri};
                console.log('profileSource = '+ source);
                // const source = { uri: 'data:image/jpeg;base64,' + response.data };
                
                if(response.name){
                    source['name'] = response.fileName
                } else {
                    paths = response.uri.split("/")
                    source['name'] = paths [paths.length-1];
                }

                if(response.type){
                    source['type'] = response.type;
                }

                imgSource = source;
            }
        });
    }`

Update Profile Img function (button onclick)
`_onUpdateProfile() {
        var sb = SendBird.getInstance();
        var _Self = this;
        
        sb.updateCurrentUserInfoWithProfileImage(_Self.state.nickname, imgSource, (user, error) => {
            if(error){
                console.log(error);
                return;
            }
            ToastAndroid.show('Profile Updated!', ToastAndroid.LONG);
            this.props.navigator.replace({name:'groupChannel', refresh: _Self.props.route.refresh});
        });
    }`
