### ISSUE TITLE
Getting "Cannot read property 'length' of undefined" when trying to retrieve channel list

### ISSUE THREAD

**Issue by just-tom** [smilefam/SendBird-JavaScript#68]
Hi guys,

Trying to implement the JS SDK and trying to retrieve a list of group channels filtered by user id as shown here: https://docs.sendbird.com/javascript/group_channel#3_filter_group_channels_by_user_ids

Here is the code:
`const groupChannelListQuery = SendBirdClient.GroupChannel.createMyGroupChannelListQuery();
        groupChannelListQuery.userIdsIncludeFilter = [username];
        groupChannelListQuery.userIdsIncludeFilterQueryType = 'OR';
        return new Promise((resolve, reject) => {
            return groupChannelListQuery.next((channels, error) => {
                if (error) reject(error)
                resolve(channels)
            })
        });`

Unfortunately when trying to get the channels im getting the error "Cannot read property 'length' of undefined" - i can't make out where this is being cause because i'm using the minified version installed with yarn.

I only have 1 Group channel and i know this user is definitely a part of it. Using version 3.0.91 according to yarn.

Any help will be much appreciated

**Comment by just-tom** [comment]
![screen shot 2018-12-11 at 01 03 05](https://user-images.githubusercontent.com/12802934/49771347-8e97ff80-fce0-11e8-8712-db6c1ccea250.png)
 
Here is the full error if it helps

**Comment by chrisallo** [comment]
I got some correction for you below.
```js
// groupChannelListQuery.userIdsIncludeFilterQueryType = ‘OR’;
groupChannelListQuery.queryType = sb.GroupChannelListQuery.QueryType.OR;
...
new Promise((resolve, reject) => {
  return groupChannelListQuery.next((channels, error) => {
    if(error) reject(error);
    else resolve(channels); // ‘else’ is missing here
  });
});
```
The error is not related to the correction above. I am checking the error in SDK and back after spotting the issue. Thanks!

**Comment by Alchemist85K** [comment]
Hi @just-tom 

We reproduced this error. We'll fix the bug in the next version(v3.0.92).
Thank you for your interest in SendBird SDK. :)

**Comment by chrisallo** [comment]
My bad. I edited the code where 'else' is missing in `Promise`.

**Comment by chrisallo** [comment]
I think it's fixed now. So close the issue.
