### ISSUE TITLE
pushNotification for react-native apps

### ISSUE THREAD

**Issue by karthickvkumar** [smilefam/SendBird-JavaScript#8]
Hi @sf-harry-kim @sf-john-kim @sf-jed-kyung, thanks for this awesome package. In react-native messenger is working fine, but we find difficult in using sendbird pushNotification for react-native apps. We coudnt find any documentation for pushNotification in Javascript SDK. It would be more helpful, if you provide any solution. 

Thanks in Advance

**Comment by sf-victor-lee** [comment]
hi @karthickvkumar.

You can find the document in javascript SDK Document: [15. Register / Unregister Token](https://sendbird.gitbooks.io/sendbird-javascript-sdk/content/sdk_function_common.html)

Thanks!

**Comment by nickmaxwell10** [comment]
^ Got a 404 on the above link

**Comment by mcmar** [comment]
@sf-victor-lee Please update your link. I need to register a gcm/apns token in the Javascript SDK w/ react-native. There's no documentation whatsoever on Sendbird's site for how to do this.

**Comment by Alchemist85K** [comment]
Hi @mcmar. 
That document is no longer used.
Please see the link below.

https://docs.sendbird.com/javascript
https://github.com/smilefam/SendBird-SDK-JavaScript/blob/master/SendBird.d.ts

Thank you for your interest in SendBird SDK.

**Comment by mcmar** [comment]
Thank you @Alchemist85K ! You're my personal lord and savior.
FWIW I scoured the JS documentation at https://docs.sendbird.com/javascript several times over and it didn't document registering push notification tokens.
It looks like I should be using https://github.com/smilefam/SendBird-SDK-JavaScript/blob/master/SendBird.d.ts for documentation and only using https://docs.sendbird.com/javascript for examples.

**Comment by Alchemist85K** [comment]
@mcmar 
Thank you for your feedback.
We'll update this document soon.
