### ISSUE TITLE
Can you clarify about the setDoNotDisturb method?

### ISSUE THREAD

**Issue by reactionic127** [smilefam/SendBird-JavaScript#82]
@chrisallo @Alchemist85K 
First of all, thanks for this useful Javascript SDK. Sendbird is awesome chat library.
I am going to snooze push notification for some period(ex: 5mins) after I received the message when the app in background mode.
But I am not sure how to use setDoNotDisturb method in this case.
FYI, we are using OneSignal for push notification not using React Native FCM since original push notifications are implemented by OneSignal.
Could you kindly clarify about the process how to implement the setDoNotDisturb functionality?
Thanks.

**Comment by imju** [comment]
@reactionic127 
Since you are not using the push notification from SendBird, you can skip the part to upload the push token then there won't be any push notifications issued from SendBird.  This will be simpler than using DND setting.  Hope this helps!

**Comment by reactionic127** [comment]
@imju 
I am getting notification from Sendbird and I need to handle it

**Comment by imju** [comment]
The DND is used to turn off a period of time of a day or a block of time on repeated fashion.  You want to use DND for snoozing a few hours or blocking notifications for during your sleep. 

As you mentioned that the app already has a push notification provider and want to turn off notifications from SendBird server, the DND setting is not enough for this case.  The most effective way is to not register push tokens. 
If you are still receiving the notifications then there may have been push tokens registered previously, 
unregisterGCMPushTokenAllForCurrentUser or unregisterAPNSPushTokenAllForCurrentUser can remove the previous tokens for the user.  
This blocks SendBird from sending push notifications the device effectively.  

If you are looking for another way, then please check Trigger options for users. **off** value with setPushTriggerOption will turn off all the push notifications for the user.
