### ISSUE TITLE
not able to type chat

### ISSUE THREAD

**Issue by yadav-durgesh** [smilefam/SendBird-JavaScript#83]
Hi, I am not able to chat with another user in android phone, as the keyboard closes automatically when I try to chat.

**Comment by Alchemist85K** [comment]
@yada

What sample are you using?
Please explain the sample you are currently using and the situation in more detail.

Thank you for your interest in SendBird SDK :)

**Comment by jonathanium** [comment]
@Alchemist85K ,  the issue is with these two lines on the FlatList props.  
`  onEndReached={() => this._getMessageList(false)}`
`  onEndReachedThreshold={0}` 

Sometimes clicking on the input is assumed as reaching the Threshold, and the component gets loaded again, what forces keyboard dismiss

**Comment by chrisallo** [comment]
Will update the sample with the fix.

**Comment by yadav-durgesh** [comment]
@jonathanium great thanks.
