### ISSUE TITLE
Share Image With Caption

### ISSUE THREAD

**Issue by IndieAppDevs** [smilefam/SendBird-JavaScript#86]
I explored a lot and did not find a way to bound caption with an image while sharing,I did not found it any documentation or sample. Since we are using sendbird and must need this future ASAP. Can anyone please tell me can you fix this issue or if it is already there please point me out.

**Comment by Alchemist85K** [comment]
@IndieAppDevs 

We don't support a bound caption on "sendFileMessage".

If you use our product and have a question, you can be supported by our homepage. 
https://help.sendbird.com/hc/en-us/requests/new

Thank you for your interest in SendBird SDK :)

**Comment by janna-sendbird** [comment]
@IndieAppDevs If you are looking to add a caption in general, please follow the answer provided here:
https://github.com/smilefam/SendBird-iOS/issues/60
> Send a file message with data that has the caption.
> 
> If you want to send a file message with an `SBDFileMessageParams`, set the caption in the data of the `SBDFileMessageParams` object:
> https://docs.sendbird.com/ref/ios/Classes/SBDBaseMessageParams.html#//api/name/data
> 
> If you want to use a method to send a file message, use the method that has a data parameter:
> https://docs.sendbird.com/ref/ios/Classes/SBDBaseChannel.html#//api/name/sendFileMessageWithBinaryData:filename:type:size:thumbnailSizes:data:customType:progressHandler:completionHandler:
> 
> You can see the caption in the data of the file message:
> https://docs.sendbird.com/ref/ios/Classes/SBDBaseMessage.html#//api/name/data
