### ISSUE TITLE
Unread message count on a group channel

### ISSUE THREAD

**Issue by alyssawolejko** [smilefam/SendBird-JavaScript#89]
Currently the `unreadMessageCount` field on the Channel object is showing an unread count for **all the users** in the group channel. 

For example, if User A and User B are in a group channel, User A sends a message to the channel... my current user is User A; the channel now has an `unreadMessageCount` of 1 (referring to UserB not reading the message yet).

How do I get only the current user's `unreadMessageCount` on a group channel?

**Comment by supertopoz** [comment]
@alyssawolejko . The unreadMessageCount for the current user comes can be accessed by calling the [getTotalUnreadMessageCount()](https://docs.sendbird.com/javascript/group_channel_advanced#3_retrieve_number_of_unread_messages_in_a_channel)
