### ISSUE TITLE
http dependency is missing

### ISSUE THREAD

**Issue by eugenehp** [smilefam/SendBird-JavaScript#9]
<img width="487" alt="screen shot 2016-06-28 at 16 24 21" src="https://cloud.githubusercontent.com/assets/1857263/16435907/650c18c6-3d4e-11e6-8d7a-0f54fd3dc6ce.png">

```
"dependencies": {
    "react-native": "^0.20.0",
    "react-native-button": "1.4.2",
    "react-native-gifted-messenger": "0.0.18",
    "react-native-gifted-spinner": "0.0.3",
    "react-native-popup": "0.5.2",
    "sendbird": "^2.4.14"
  },
```

**Comment by donaminos** [comment]
+1

**Comment by thepav** [comment]
Also have this problem.

**Comment by mhanselm** [comment]
+1

**Comment by nickmaxwell10** [comment]
+1

**Comment by nickmaxwell10** [comment]
Hey guys, I got the demo project to run by removing the following from the node_modules/sendbird/SendBird.min.js file..

`var i=require("http"),a=require("https"),o=new i.Agent({keepAlive:!0,keepAliveMsecs:6e4}),c=new a.Agent({keepAlive:!0,keepAliveMsecs:6e4}),u={};u.httpAgent=o,u.httpsAgent=c,t.nodejsSet(u)`

Not sure if there are any detrimental effects.. But most features seem to work.

**Comment by sf-jin-ku** [comment]
It should be resolved in our latest V3 SDK example.
Please upgrade your SDK to V3 and take a look at the new example
Thanks!
